# Generated by Django 3.2.20 on 2023-07-11 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 14, 58, 29, 747015, tzinfo=utc)),
        ),
    ]
