# Generated by Django 3.2.20 on 2023-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('위험', '위험'), ('추행', '추행'), ('폭행', '폭행'), ('침입', '침입')], max_length=20),
        ),
    ]
